import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, Archive, ArrowLeft, ArrowUpRight, BarChart3, Bell, BriefcaseBusiness, Check, ChevronDown, Code2, Download, Edit3, FileText, FolderKanban, Home, Inbox, LayoutDashboard, Mail, Menu, MessageSquare, MoreHorizontal, PanelLeftClose, Plus, Search, Send, Settings, Sparkles, Trash2, UserRound, Wrench, X } from 'lucide-react';
import '../styles/admin.css';

const seed = {
  Home: [{ id: 1, name: 'Hero headline', detail: 'Full Stack Developer & UI/UX Designer' }, { id: 2, name: 'Short introduction', detail: 'I build polished digital experiences.' }],
  About: [{ id: 1, name: 'Biography', detail: 'A developer focused on thoughtful products and memorable interfaces.' }, { id: 2, name: 'Location', detail: 'Pakistan · Available worldwide' }],
  Services: [{ id: 1, name: 'UI/UX Design', detail: 'Design · Order 1' }, { id: 2, name: 'Web Development', detail: 'Development · Order 2' }, { id: 3, name: 'Mobile App Development', detail: 'Development · Order 3' }],
  Skills: [{ id: 1, name: 'React', detail: 'Frontend · 92%' }, { id: 2, name: 'Node.js', detail: 'Backend · 86%' }, { id: 3, name: 'UI Design', detail: 'Design · 90%' }],
  Projects: [{ id: 1, name: 'Kinetic Finance', detail: 'Finance platform · Featured' }, { id: 2, name: 'WeConnect', detail: 'Web application · Completed' }, { id: 3, name: 'Doctor HUB', detail: 'Healthcare platform · Completed' }],
};
const nav = [['Dashboard', LayoutDashboard], ['Home', Home], ['About', UserRound], ['Services', Wrench], ['Skills', Code2], ['Projects', FolderKanban], ['Messages', Mail]];
const messages = [{ id: 1, name: 'Sarah Miller', email: 'sarah@northstar.co', subject: 'Product design opportunity', body: 'Hi Uzair, I love the work in your portfolio. Are you open to discussing a product design project?', date: '2 min ago', read: false }, { id: 2, name: 'Bilal Khan', email: 'bilal@studio.pk', subject: 'Website quotation', body: 'I am looking for a modern website for our growing studio. Could we arrange a call?', date: '1 hr ago', read: false }, { id: 3, name: 'Mia Cooper', email: 'mia@luminate.com', subject: 'Great portfolio', body: 'Just wanted to say your visual craft is excellent. Keep making great things.', date: 'Yesterday', read: true }];

function useCollection(section) {
  const key = `portfolio-admin-${section.toLowerCase()}`;
  const [items, setItems] = useState(() => { try { return JSON.parse(localStorage.getItem(key)) || seed[section] || []; } catch { return seed[section] || []; } });
  useEffect(() => localStorage.setItem(key, JSON.stringify(items)), [items, key]);
  return [items, setItems];
}

export default function Admin() {
  const [active, setActive] = useState('Dashboard'); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [notice, setNotice] = useState('');
  const notify = (text) => { setNotice(text); window.setTimeout(() => setNotice(''), 2400); };
  return <div className="admin-shell">
    <aside className={`admin-sidebar ${collapsed ? 'is-collapsed' : ''} ${mobileOpen ? 'is-open' : ''}`}>
      <div className="brand-row"><div className="brand-mark"><Sparkles size={18}/></div><span className="brand-name">Portfolio <span>Admin</span></span><button className="collapse-btn" onClick={() => setCollapsed(!collapsed)} aria-label="Collapse navigation"><PanelLeftClose size={18}/></button><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={20}/></button></div>
      <nav className="side-nav"><p className="nav-label">Content management</p>{nav.map(([name, Icon]) => <button key={name} onClick={() => { setActive(name); setMobileOpen(false); }} className={`nav-item ${active === name ? 'active' : ''}`}><Icon size={18}/><span>{name}</span>{name === 'Messages' && <b>2</b>}</button>)}<p className="nav-label second">Workspace</p><button className="nav-item" onClick={() => notify('Settings panel coming next')}><Settings size={18}/><span>Portfolio settings</span></button></nav>
      <div className="sidebar-foot"><a className="back-site" href="/"><ArrowLeft size={16}/><span>Back to website</span></a><button className="profile-mini"><span className="avatar">UA</span><span><strong>Uzair Ahmad</strong><small>Administrator</small></span><MoreHorizontal size={18}/></button></div>
    </aside>
    <div className={`mobile-backdrop ${mobileOpen ? 'visible' : ''}`} onClick={() => setMobileOpen(false)}/>
    <main className="admin-main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu size={21}/></button><div className="crumb"><span>Portfolio Admin</span><ChevronDown size={14}/><strong>{active}</strong></div><div className="top-actions"><button className="command-search"><Search size={16}/><span>Search workspace</span><kbd>⌘ K</kbd></button><button className="icon-button" onClick={() => notify('You have 2 unread messages')}><Bell size={19}/><i/></button></div></header>
      {active === 'Dashboard' ? <Dashboard setActive={setActive} notify={notify}/> : active === 'Messages' ? <Messages notify={notify}/> : <ContentEditor section={active} notify={notify}/>}</main>
    <AnimatePresence>{notice && <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}} className="admin-toast"><Check size={15}/>{notice}</motion.div>}</AnimatePresence>
  </div>;
}

function Dashboard({ setActive, notify }) {
  const cards = [['Total services', '6', Wrench, 'blue'], ['Skills', '18', Code2, 'purple'], ['Total projects', '11', FolderKanban, 'cyan'], ['Contact messages', '5', Mail, 'pink']];
  return <div className="dashboard-content"><section className="welcome-row"><div><p className="eyebrow"><span/> LIVE PORTFOLIO</p><h1>Admin Dashboard <span>✦</span></h1><p className="subtitle">Overview of your portfolio content and quick actions.</p></div><div className="date-actions"><button className="primary-button" onClick={() => setActive('Services')}><Plus size={18}/> Add service</button><button className="secondary-button" onClick={() => setActive('Projects')}><Plus size={18}/> Add project</button></div></section>
    <section className="metrics-grid">{cards.map(([label, value, Icon, tint], i) => <motion.article initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} className="metric-card" key={label}><div className={`metric-icon ${tint}`}><Icon size={20}/></div><div className="metric-top"><span>{label}</span><MoreHorizontal size={17}/></div><strong>{value}</strong><p><em><ArrowUpRight size={13}/> 12.5%</em> vs last month</p></motion.article>)}</section>
    <section className="analytics-grid"><article className="panel traffic-panel"><div className="panel-heading"><div><p>ANALYTICS</p><h2>Portfolio visitors</h2></div><button className="range-button">Last 30 days <ChevronDown size={14}/></button></div><div className="audience-stats"><div><span>Total visitors</span><strong>48,294</strong><em><ArrowUpRight size={13}/> 18.2%</em></div><div><span>Resume downloads</span><strong>1,284</strong><em><ArrowUpRight size={13}/> 22.4%</em></div></div><div className="chart-area"><div className="chart-y"><span>2k</span><span>1.5k</span><span>1k</span><span>500</span><span>0</span></div><svg viewBox="0 0 780 220" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#7c5cff" stopOpacity=".35"/><stop offset="1" stopColor="#7c5cff" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 190 C35 175 50 180 75 152 S120 145 145 163 S190 123 215 139 S258 130 282 104 S329 130 355 111 S400 73 427 91 S469 105 492 68 S535 71 561 86 S605 34 630 54 S677 84 704 38 S748 34 780 18 L780 220 L0 220 Z"/><path className="line" d="M0 190 C35 175 50 180 75 152 S120 145 145 163 S190 123 215 139 S258 130 282 104 S329 130 355 111 S400 73 427 91 S469 105 492 68 S535 71 561 86 S605 34 630 54 S677 84 704 38 S748 34 780 18"/></svg><div className="chart-x"><span>Jun 18</span><span>Jun 24</span><span>Jun 30</span><span>Jul 06</span><span>Jul 12</span><span>Jul 17</span></div></div></article>
    <article className="panel performance-panel"><div className="panel-heading"><div><p>QUICK ACTIONS</p><h2>Manage content</h2></div></div><div className="quick-grid"><button onClick={() => setActive('Home')}><Home/><span>Edit home</span></button><button onClick={() => setActive('About')}><UserRound/><span>Edit about</span></button><button onClick={() => setActive('Messages')}><Inbox/><span>View inbox</span></button><button onClick={() => notify('Portfolio link copied')}><Send/><span>Share portfolio</span></button></div><button className="outline-wide" onClick={() => notify('Analytics report is ready to download')}><Download size={16}/> Export report</button></article></section>
  </div>;
}

function ContentEditor({ section, notify }) {
  const [items, setItems] = useCollection(section); const [editing, setEditing] = useState(null); const [form, setForm] = useState({ name: '', detail: '' });
  const start = (item) => { setEditing(item?.id || 'new'); setForm(item ? { name:item.name, detail:item.detail } : { name:'', detail:'' }); };
  const save = (event) => { event.preventDefault(); if (!form.name.trim() || !form.detail.trim()) return notify('Please complete both fields'); if (editing === 'new') setItems([...items, { id:Date.now(), ...form }]); else setItems(items.map(item => item.id === editing ? { ...item, ...form } : item)); setEditing(null); notify(`${section} ${editing === 'new' ? 'added' : 'updated'} successfully`); };
  const remove = (id) => { setItems(items.filter(item => item.id !== id)); notify(`${section.slice(0, -1) || section} removed`); };
  return <div className="dashboard-content manager-page"><section className="welcome-row"><div><p className="eyebrow"><span/> PORTFOLIO CONTENT</p><h1>{section} <span>✦</span></h1><p className="subtitle">Add, edit, reorder, or remove content displayed on your portfolio.</p></div><button className="primary-button" onClick={() => start()}><Plus size={18}/> Add {section === 'Home' || section === 'About' ? 'content' : section.slice(0,-1)}</button></section>
    <section className="manager-layout"><article className="panel content-list"><div className="panel-heading"><div><p>ACTIVE CONTENT</p><h2>{items.length} {section.toLowerCase()} item{items.length === 1 ? '' : 's'}</h2></div><Search size={17} className="muted-icon"/></div>{items.length ? <div className="manage-items">{items.map((item, i) => <motion.div layout className="manage-item" key={item.id}><span className="item-number">{String(i+1).padStart(2,'0')}</span><div><strong>{item.name}</strong><p>{item.detail}</p></div><div className="item-actions"><button onClick={() => start(item)} aria-label={`Edit ${item.name}`}><Edit3 size={16}/></button><button className="danger" onClick={() => remove(item.id)} aria-label={`Remove ${item.name}`}><Trash2 size={16}/></button></div></motion.div>)}</div> : <div className="empty-state"><Archive size={28}/><strong>No {section.toLowerCase()} yet</strong><span>Create your first item to show it on your portfolio.</span></div>}</article>
    <article className="panel editor-panel"><div className="panel-heading"><div><p>{editing ? 'CONTENT EDITOR' : 'GET STARTED'}</p><h2>{editing === 'new' ? `Add ${section}` : editing ? `Edit ${section}` : `Select an item`}</h2></div></div>{editing ? <form className="content-form" onSubmit={save}><label>Title or name<input autoFocus value={form.name} onChange={e => setForm({...form,name:e.target.value})} placeholder={`Enter ${section.toLowerCase()} name`}/></label><label>{section === 'Projects' ? 'Description / status' : 'Details'}<textarea value={form.detail} onChange={e => setForm({...form,detail:e.target.value})} placeholder="Add a short description" rows="5"/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Cancel</button><button className="primary-button" type="submit"><Check size={16}/> Save changes</button></div></form> : <div className="editor-empty"><Edit3 size={25}/><p>Select an item to edit it, or create a new one.</p><button className="text-button" onClick={() => start()}><Plus size={15}/> Create new item</button></div>}</article></section></div>;
}

function Messages({ notify }) {
  const [items, setItems] = useState(messages); const [selected, setSelected] = useState(items[0]); const [filter, setFilter] = useState('');
  const visible = useMemo(() => items.filter(m => `${m.name} ${m.subject}`.toLowerCase().includes(filter.toLowerCase())), [items, filter]);
  const open = (message) => { setSelected({...message, read:true}); setItems(items.map(m => m.id === message.id ? {...m,read:true} : m)); };
  const remove = (id) => { const next=items.filter(m=>m.id!==id); setItems(next); setSelected(next[0] || null); notify('Message deleted'); };
  return <div className="dashboard-content manager-page"><section className="welcome-row"><div><p className="eyebrow"><span/> CONTACT INBOX</p><h1>Messages <span>✦</span></h1><p className="subtitle">Read, respond to, and organise incoming portfolio enquiries.</p></div><button className="secondary-button" onClick={() => notify('Inbox refreshed')}><Activity size={16}/> Refresh</button></section><section className="panel inbox-panel"><div className="inbox-sidebar"><div className="inbox-search"><Search size={16}/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search messages"/></div><div className="message-list">{visible.map(message => <button onClick={() => open(message)} className={`message-preview ${selected?.id === message.id ? 'selected':''} ${!message.read ? 'unread':''}`} key={message.id}><div><strong>{message.name}</strong><time>{message.date}</time></div><b>{message.subject}</b><span>{message.body}</span></button>)}</div></div>{selected ? <article className="message-detail"><div className="message-detail-head"><div className="sender-avatar">{selected.name.split(' ').map(n=>n[0]).join('')}</div><div><strong>{selected.name}</strong><span>{selected.email}</span></div><time>{selected.date}</time></div><h2>{selected.subject}</h2><p>{selected.body}</p><div className="message-controls"><button className="secondary-button" onClick={() => notify(`Reply composer opened for ${selected.name}`)}><MessageSquare size={16}/> Reply</button><button className="danger-button" onClick={() => remove(selected.id)}><Trash2 size={16}/> Delete</button></div></article> : <div className="editor-empty">No message selected.</div>}</section></div>;
}
